### PR TITLE
Added Support to laravel 10.*

### PR DESCRIPTION
**Pull request by Stephan-MC**

### CODE REVIEW

**Comment by Stephan-MC** [comment]
hello....

**Comment by Stephan-MC** [comment]
please merge this pull request to add support to laravel 10

**Comment by Stephan-MC** [comment]
Thanks bro…. I’m great fan of your work 😉 Sent from my iPhoneOn Jul 10, 2023, at 09:50, ndifon ***@***.***> wrote:﻿
Hello @Stephan-MC .
I'll check this out later this evening and get back to you.

**Comment by yondifon** [comment]
Thanks, @Stephan-MC 
Here's the release: https://github.com/yondifon/laravel-mesomb/releases/tag/1.6

You should consider switching to https://github.com/hachther/laravel-mesomb (Supported by the hachther team themselves.

**Comment by Stephan-MC** [comment]
Awesome, thanks! i really appreciate the work you did

**Pull request merged**
